#!/usr/bin/sh

if [ $# -lt 2 ]
then
	echo "Usage is: $0 <end> <port no.>"
	exit 
fi
. /etc/pbs.conf

echo "Stopping moms and deleting all nodes"
#stop everything and remove all nodes
pkill pbs_mom
sleep 1
pkill -9 pbs_mom

for node in `pbsnodes -av | grep ^mom`
do
	$PBS_EXEC/bin/qmgr -c "d n $node"
done
echo "Deleted all nodes"

l=$1
n=1
port=$2
mom_name=`hostname`
if [ $# -eq 3 ]; then
	mom_name=$3
fi

. /etc/pbs.conf

ulimit -n 10000
ulimit -c unlimited

echo "Moms required to be created are from $n to $l with port starting from $port"

while [ $n -le $l ]
do
	#echo "Adding node mom$n"
	$PBS_EXEC/bin/qmgr -c "c n mom$n mom=$mom_name, port=$port"

	port=`expr $port + 5`
	n=`expr $n + 1`
done

pbs_home=$PBS_HOME

n=1
port=$2
echo editing pbs.conf file and mom_priv/config
while [ $n -le $l ]
do
	echo starting mom $n

	docker run --net=host -d --rm centos_mom bash -c "/opt/pbs/sbin/start_mom $port"
	
	port=`expr $port + 5`
	n=`expr $n + 1`
done

echo "Done"
