#ifndef PBS_IFL_VERIFIER_H
#define PBS_IFL_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef PBS_IFL_READER_H
#include "pbs_ifl_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int PBS_ifl_Header_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Attribute_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Extend_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Qjob_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Req_verify_table(flatcc_table_verifier_descriptor_t *td);

static int PBS_ifl_ReqBody_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_Qjob_verify_table); /* Qjob */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_Header_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* protType */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* batchId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* user */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Header_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Header_identifier, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Header_type_identifier, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Header_verify_table);
}

static int PBS_ifl_Attribute_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* resc */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* value */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* op */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Attribute_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Attribute_identifier, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Attribute_type_identifier, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Attribute_verify_table);
}

static int PBS_ifl_Extend_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* extend */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Extend_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Extend_identifier, &PBS_ifl_Extend_verify_table);
}

static inline int PBS_ifl_Extend_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Extend_type_identifier, &PBS_ifl_Extend_verify_table);
}

static inline int PBS_ifl_Extend_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Extend_verify_table);
}

static inline int PBS_ifl_Extend_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Extend_verify_table);
}

static int PBS_ifl_Qjob_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* destin */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Qjob_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Qjob_identifier, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Qjob_type_identifier, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Qjob_verify_table);
}

static int PBS_ifl_Req_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &PBS_ifl_Header_verify_table) /* hdr */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &PBS_ifl_ReqBody_union_verifier) /* body */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 3, 0, &PBS_ifl_Extend_verify_table) /* extend */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Req_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Req_identifier, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Req_type_identifier, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Req_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PBS_IFL_VERIFIER_H */
