#ifndef PBS_IFL_VERIFIER_H
#define PBS_IFL_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef PBS_IFL_READER_H
#include "pbs_ifl_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int PBS_ifl_Header_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Attribute_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Extend_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Qjob_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Jobfile_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Jobid_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Manage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Msg_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_DmnCmd_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Signal_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Stat_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Spawn_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_AuthMunge_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_AuthResvPort_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Auth_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Move_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Run_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_SchedDefRep_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Select_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Track_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Register_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_CopyHook_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_FilePair_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_CopyFile_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Req_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_StatResp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_SelectRespBody_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_StatRespBody_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Resp_verify_table(flatcc_table_verifier_descriptor_t *td);

static int PBS_ifl_AuthInfo_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_AuthMunge_verify_table); /* AuthMunge */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_ReqBody_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_Qjob_verify_table); /* Qjob */
    case 2: return flatcc_verify_union_table(ud, PBS_ifl_Jobfile_verify_table); /* Jobfile */
    case 3: return flatcc_verify_union_table(ud, PBS_ifl_Jobid_verify_table); /* Jobid */
    case 4: return flatcc_verify_union_table(ud, PBS_ifl_Manage_verify_table); /* Manage */
    case 5: return flatcc_verify_union_table(ud, PBS_ifl_Msg_verify_table); /* Msg */
    case 6: return flatcc_verify_union_table(ud, PBS_ifl_DmnCmd_verify_table); /* DmnCmd */
    case 7: return flatcc_verify_union_table(ud, PBS_ifl_Signal_verify_table); /* Signal */
    case 8: return flatcc_verify_union_table(ud, PBS_ifl_Stat_verify_table); /* Stat */
    case 9: return flatcc_verify_union_table(ud, PBS_ifl_Spawn_verify_table); /* Spawn */
    case 10: return flatcc_verify_union_table(ud, PBS_ifl_Auth_verify_table); /* Auth */
    case 11: return flatcc_verify_union_table(ud, PBS_ifl_Move_verify_table); /* Move */
    case 12: return flatcc_verify_union_table(ud, PBS_ifl_Run_verify_table); /* Run */
    case 13: return flatcc_verify_union_table(ud, PBS_ifl_SchedDefRep_verify_table); /* SchedDefRep */
    case 14: return flatcc_verify_union_table(ud, PBS_ifl_Select_verify_table); /* Select */
    case 15: return flatcc_verify_union_table(ud, PBS_ifl_Track_verify_table); /* Track */
    case 16: return flatcc_verify_union_table(ud, PBS_ifl_Register_verify_table); /* Register */
    case 17: return flatcc_verify_union_table(ud, PBS_ifl_CopyHook_verify_table); /* CopyHook */
    case 18: return flatcc_verify_union_table(ud, PBS_ifl_CopyFile_verify_table); /* CopyFile */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_RespBody_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_string(ud); /* text */
    case 2: return flatcc_verify_union_table(ud, PBS_ifl_SelectRespBody_verify_table); /* selects */
    case 3: return flatcc_verify_union_table(ud, PBS_ifl_StatRespBody_verify_table); /* stats */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_Header_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* protType */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* batchId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* user */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Header_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Header_identifier, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Header_type_identifier, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Header_verify_table);
}

static int PBS_ifl_Attribute_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* resc */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* value */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* op */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Attribute_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Attribute_identifier, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Attribute_type_identifier, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Attribute_verify_table);
}

static int PBS_ifl_Extend_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* extend */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Extend_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Extend_identifier, &PBS_ifl_Extend_verify_table);
}

static inline int PBS_ifl_Extend_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Extend_type_identifier, &PBS_ifl_Extend_verify_table);
}

static inline int PBS_ifl_Extend_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Extend_verify_table);
}

static inline int PBS_ifl_Extend_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Extend_verify_table);
}

static int PBS_ifl_Qjob_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* destin */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Qjob_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Qjob_identifier, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Qjob_type_identifier, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Qjob_verify_table);
}

static int PBS_ifl_Jobfile_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* seq */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* size */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 4, 0) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Jobfile_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Jobfile_identifier, &PBS_ifl_Jobfile_verify_table);
}

static inline int PBS_ifl_Jobfile_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Jobfile_type_identifier, &PBS_ifl_Jobfile_verify_table);
}

static inline int PBS_ifl_Jobfile_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Jobfile_verify_table);
}

static inline int PBS_ifl_Jobfile_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Jobfile_verify_table);
}

static int PBS_ifl_Jobid_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Jobid_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Jobid_identifier, &PBS_ifl_Jobid_verify_table);
}

static inline int PBS_ifl_Jobid_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Jobid_type_identifier, &PBS_ifl_Jobid_verify_table);
}

static inline int PBS_ifl_Jobid_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Jobid_verify_table);
}

static inline int PBS_ifl_Jobid_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Jobid_verify_table);
}

static int PBS_ifl_Manage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* cmd */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* objType */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* objName */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Manage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Manage_identifier, &PBS_ifl_Manage_verify_table);
}

static inline int PBS_ifl_Manage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Manage_type_identifier, &PBS_ifl_Manage_verify_table);
}

static inline int PBS_ifl_Manage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Manage_verify_table);
}

static inline int PBS_ifl_Manage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Manage_verify_table);
}

static int PBS_ifl_Msg_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* fileInd */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* text */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Msg_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Msg_identifier, &PBS_ifl_Msg_verify_table);
}

static inline int PBS_ifl_Msg_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Msg_type_identifier, &PBS_ifl_Msg_verify_table);
}

static inline int PBS_ifl_Msg_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Msg_verify_table);
}

static inline int PBS_ifl_Msg_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Msg_verify_table);
}

static int PBS_ifl_DmnCmd_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* cmd */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_DmnCmd_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_DmnCmd_identifier, &PBS_ifl_DmnCmd_verify_table);
}

static inline int PBS_ifl_DmnCmd_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_DmnCmd_type_identifier, &PBS_ifl_DmnCmd_verify_table);
}

static inline int PBS_ifl_DmnCmd_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_DmnCmd_verify_table);
}

static inline int PBS_ifl_DmnCmd_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_DmnCmd_verify_table);
}

static int PBS_ifl_Signal_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* sigName */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Signal_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Signal_identifier, &PBS_ifl_Signal_verify_table);
}

static inline int PBS_ifl_Signal_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Signal_type_identifier, &PBS_ifl_Signal_verify_table);
}

static inline int PBS_ifl_Signal_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Signal_verify_table);
}

static inline int PBS_ifl_Signal_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Signal_verify_table);
}

static int PBS_ifl_Stat_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobIds */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Stat_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Stat_identifier, &PBS_ifl_Stat_verify_table);
}

static inline int PBS_ifl_Stat_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Stat_type_identifier, &PBS_ifl_Stat_verify_table);
}

static inline int PBS_ifl_Stat_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Stat_verify_table);
}

static inline int PBS_ifl_Stat_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Stat_verify_table);
}

static int PBS_ifl_Spawn_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 0) /* argv */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 2, 0) /* envp */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Spawn_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Spawn_identifier, &PBS_ifl_Spawn_verify_table);
}

static inline int PBS_ifl_Spawn_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Spawn_type_identifier, &PBS_ifl_Spawn_verify_table);
}

static inline int PBS_ifl_Spawn_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Spawn_verify_table);
}

static inline int PBS_ifl_Spawn_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Spawn_verify_table);
}

static int PBS_ifl_AuthMunge_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* key */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_AuthMunge_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_AuthMunge_identifier, &PBS_ifl_AuthMunge_verify_table);
}

static inline int PBS_ifl_AuthMunge_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_AuthMunge_type_identifier, &PBS_ifl_AuthMunge_verify_table);
}

static inline int PBS_ifl_AuthMunge_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_AuthMunge_verify_table);
}

static inline int PBS_ifl_AuthMunge_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_AuthMunge_verify_table);
}

static int PBS_ifl_AuthResvPort_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* port */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_AuthResvPort_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_AuthResvPort_identifier, &PBS_ifl_AuthResvPort_verify_table);
}

static inline int PBS_ifl_AuthResvPort_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_AuthResvPort_type_identifier, &PBS_ifl_AuthResvPort_verify_table);
}

static inline int PBS_ifl_AuthResvPort_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_AuthResvPort_verify_table);
}

static inline int PBS_ifl_AuthResvPort_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_AuthResvPort_verify_table);
}

static int PBS_ifl_Auth_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &PBS_ifl_AuthInfo_union_verifier) /* info */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Auth_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Auth_identifier, &PBS_ifl_Auth_verify_table);
}

static inline int PBS_ifl_Auth_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Auth_type_identifier, &PBS_ifl_Auth_verify_table);
}

static inline int PBS_ifl_Auth_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Auth_verify_table);
}

static inline int PBS_ifl_Auth_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Auth_verify_table);
}

static int PBS_ifl_Move_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* dest */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Move_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Move_identifier, &PBS_ifl_Move_verify_table);
}

static inline int PBS_ifl_Move_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Move_type_identifier, &PBS_ifl_Move_verify_table);
}

static inline int PBS_ifl_Move_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Move_verify_table);
}

static inline int PBS_ifl_Move_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Move_verify_table);
}

static int PBS_ifl_Run_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* dest */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* resch */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Run_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Run_identifier, &PBS_ifl_Run_verify_table);
}

static inline int PBS_ifl_Run_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Run_type_identifier, &PBS_ifl_Run_verify_table);
}

static inline int PBS_ifl_Run_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Run_verify_table);
}

static inline int PBS_ifl_Run_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Run_verify_table);
}

static int PBS_ifl_SchedDefRep_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* cmd */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* id */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* err */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* text */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_SchedDefRep_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SchedDefRep_identifier, &PBS_ifl_SchedDefRep_verify_table);
}

static inline int PBS_ifl_SchedDefRep_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SchedDefRep_type_identifier, &PBS_ifl_SchedDefRep_verify_table);
}

static inline int PBS_ifl_SchedDefRep_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_SchedDefRep_verify_table);
}

static inline int PBS_ifl_SchedDefRep_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_SchedDefRep_verify_table);
}

static int PBS_ifl_Select_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PBS_ifl_Attribute_verify_table) /* selAttrs */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &PBS_ifl_Attribute_verify_table) /* rtnAttrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Select_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Select_identifier, &PBS_ifl_Select_verify_table);
}

static inline int PBS_ifl_Select_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Select_type_identifier, &PBS_ifl_Select_verify_table);
}

static inline int PBS_ifl_Select_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Select_verify_table);
}

static inline int PBS_ifl_Select_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Select_verify_table);
}

static int PBS_ifl_Track_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* hops */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* location */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* state */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Track_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Track_identifier, &PBS_ifl_Track_verify_table);
}

static inline int PBS_ifl_Track_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Track_type_identifier, &PBS_ifl_Track_verify_table);
}

static inline int PBS_ifl_Track_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Track_verify_table);
}

static inline int PBS_ifl_Track_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Track_verify_table);
}

static int PBS_ifl_Register_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* owner */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* server */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* parent */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* child */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 2, 2) /* op */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 8, 8) /* cost */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Register_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Register_identifier, &PBS_ifl_Register_verify_table);
}

static inline int PBS_ifl_Register_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Register_type_identifier, &PBS_ifl_Register_verify_table);
}

static inline int PBS_ifl_Register_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Register_verify_table);
}

static inline int PBS_ifl_Register_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Register_verify_table);
}

static int PBS_ifl_CopyHook_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* seq */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* size */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* filename */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_CopyHook_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyHook_identifier, &PBS_ifl_CopyHook_verify_table);
}

static inline int PBS_ifl_CopyHook_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyHook_type_identifier, &PBS_ifl_CopyHook_verify_table);
}

static inline int PBS_ifl_CopyHook_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_CopyHook_verify_table);
}

static inline int PBS_ifl_CopyHook_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_CopyHook_verify_table);
}

static int PBS_ifl_FilePair_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* local */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* remote */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* flag */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_FilePair_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_FilePair_identifier, &PBS_ifl_FilePair_verify_table);
}

static inline int PBS_ifl_FilePair_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_FilePair_type_identifier, &PBS_ifl_FilePair_verify_table);
}

static inline int PBS_ifl_FilePair_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_FilePair_verify_table);
}

static inline int PBS_ifl_FilePair_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_FilePair_verify_table);
}

static int PBS_ifl_CopyFile_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* owener */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* user */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* group */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* flags */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 5, 0, &PBS_ifl_FilePair_verify_table) /* pairs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_CopyFile_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyFile_identifier, &PBS_ifl_CopyFile_verify_table);
}

static inline int PBS_ifl_CopyFile_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyFile_type_identifier, &PBS_ifl_CopyFile_verify_table);
}

static inline int PBS_ifl_CopyFile_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_CopyFile_verify_table);
}

static inline int PBS_ifl_CopyFile_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_CopyFile_verify_table);
}

static int PBS_ifl_Req_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &PBS_ifl_Header_verify_table) /* hdr */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &PBS_ifl_ReqBody_union_verifier) /* body */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 3, 0, &PBS_ifl_Extend_verify_table) /* extend */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Req_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Req_identifier, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Req_type_identifier, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Req_verify_table);
}

static int PBS_ifl_StatResp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_StatResp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatResp_identifier, &PBS_ifl_StatResp_verify_table);
}

static inline int PBS_ifl_StatResp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatResp_type_identifier, &PBS_ifl_StatResp_verify_table);
}

static inline int PBS_ifl_StatResp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_StatResp_verify_table);
}

static inline int PBS_ifl_StatResp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_StatResp_verify_table);
}

static int PBS_ifl_SelectRespBody_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_vector_field(td, 0, 0) /* ids */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_SelectRespBody_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SelectRespBody_identifier, &PBS_ifl_SelectRespBody_verify_table);
}

static inline int PBS_ifl_SelectRespBody_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SelectRespBody_type_identifier, &PBS_ifl_SelectRespBody_verify_table);
}

static inline int PBS_ifl_SelectRespBody_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_SelectRespBody_verify_table);
}

static inline int PBS_ifl_SelectRespBody_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_SelectRespBody_verify_table);
}

static int PBS_ifl_StatRespBody_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PBS_ifl_StatResp_verify_table) /* jobs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_StatRespBody_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatRespBody_identifier, &PBS_ifl_StatRespBody_verify_table);
}

static inline int PBS_ifl_StatRespBody_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatRespBody_type_identifier, &PBS_ifl_StatRespBody_verify_table);
}

static inline int PBS_ifl_StatRespBody_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_StatRespBody_verify_table);
}

static inline int PBS_ifl_StatRespBody_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_StatRespBody_verify_table);
}

static int PBS_ifl_Resp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* code */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* auxCode */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* choice */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 4, 0, &PBS_ifl_RespBody_union_verifier) /* body */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Resp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Resp_identifier, &PBS_ifl_Resp_verify_table);
}

static inline int PBS_ifl_Resp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Resp_type_identifier, &PBS_ifl_Resp_verify_table);
}

static inline int PBS_ifl_Resp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Resp_verify_table);
}

static inline int PBS_ifl_Resp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Resp_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PBS_IFL_VERIFIER_H */
