/*
 * Copyright (C) 1994-2018 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */


/**
 * @file    db_impl_job.c
 *
 * @brief
 *      Implementation of the job data access functions for postgres
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include "pbs_db.h"
#include "db_impl.h"

/**
 *@brief
 *	Save (insert/update) a new/existing job
 *
 * @param[in]	conn - The connnection handle
 * @param[in]	obj  - The job object to save
 * @param[in]	savetype - PBS_UPDATE_DB_QUICK/PBS_UPDATE_DB_FULL/PBS_INSERT_DB
 *
 * @return      Error code
 * @retval	-1 - Execution of prepared statement failed
 * @retval	 0 - Success and > 0 rows were affected
 * @retval	 1 - Execution succeeded but statement did not affect any rows
 *
 */
int
impl_db_save_job(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_job_info_t *pjob = obj->pbs_db_un.pbs_db_job;
	int numbins = 17; /* default minimum */
	as_key key; /* jobid */
	as_integer  ji_state; /* Internal copy of state */
	as_integer  ji_substate; /* job sub-state */
	as_integer  ji_svrflags; /* server flags */
	as_integer  ji_ordering; /* special scheduling ordering */
	as_integer  ji_priority; /* Internal priority */
	as_integer  ji_stime; /* time job started execution */
	as_integer  ji_endtBdry; /* estimate upper bound on end time */
	as_string   ji_queue; /* name of current queue */
	as_string   ji_destin; /* dest from qmove/route */
	as_integer  ji_un_type;
	as_integer  ji_exitstat; /* job exit status from MOM */
	as_integer  ji_quetime; /* time entered queue */
	as_integer  ji_rteretry; /* route retry time */
	as_integer  ji_fromsock; /* socket job coming over */
	as_integer  ji_fromaddr; /* host job coming from   */
	as_integer  ji_qrank;
	as_integer  ji_savetm;
	as_integer  ji_creattm;
	as_hashmap attrmap;
	as_map_policy map_policy;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	aerospike *as = (aerospike *) conn->conn_db_handle;


	if (savetype != PBS_UPDATE_DB_QUICK) numbins++; /* for attributes */	
	if (savetype == PBS_INSERT_DB) numbins++; /* for createtm */

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "job", pjob->ji_jobid);	
	as_integer_init(&ji_state, pjob->ji_state);
	as_operations_add_write(&ops, "ji_state", (as_bin_value*) &ji_state);
	as_integer_init(&ji_substate, pjob->ji_substate);
	as_operations_add_write(&ops, "ji_substate", (as_bin_value*) &ji_substate);
	as_integer_init(&ji_svrflags, pjob->ji_svrflags);
	as_operations_add_write(&ops, "ji_svrflags", (as_bin_value*) &ji_svrflags);
	as_integer_init(&ji_ordering, pjob->ji_ordering);
	as_operations_add_write(&ops, "ji_ordering", (as_bin_value*) &ji_ordering);
	as_integer_init(&ji_priority, pjob->ji_priority);
	as_operations_add_write(&ops, "ji_priority", (as_bin_value*) &ji_priority);
	as_integer_init(&ji_stime, pjob->ji_stime);
	as_operations_add_write(&ops, "ji_stime", (as_bin_value*) &ji_stime);
	as_integer_init(&ji_endtBdry, pjob->ji_endtBdry);
	as_operations_add_write(&ops, "ji_endtBdry", (as_bin_value*) &ji_endtBdry);
	as_string_init(&ji_queue, pjob->ji_queue, false);
	as_operations_add_write(&ops, "ji_queue", (as_bin_value*) &ji_queue);
	as_string_init(&ji_destin, pjob->ji_destin, false);
	as_operations_add_write(&ops, "ji_destin", (as_bin_value*) &ji_destin);
	as_integer_init(&ji_un_type, pjob->ji_un_type);
	as_operations_add_write(&ops, "ji_un_type", (as_bin_value*) &ji_un_type);
	as_integer_init(&ji_exitstat, pjob->ji_exitstat);
	as_operations_add_write(&ops, "ji_exitstat", (as_bin_value*) &ji_exitstat);
	as_integer_init(&ji_quetime, pjob->ji_quetime);
	as_operations_add_write(&ops, "ji_quetime", (as_bin_value*) &ji_quetime);
	as_integer_init(&ji_rteretry, pjob->ji_rteretry);
	as_operations_add_write(&ops, "ji_rteretry", (as_bin_value*) &ji_rteretry);
	as_integer_init(&ji_fromsock, pjob->ji_fromsock);
	as_operations_add_write(&ops, "ji_fromsock", (as_bin_value*) &ji_fromsock);
	as_integer_init(&ji_fromaddr, pjob->ji_fromaddr);
	as_operations_add_write(&ops, "ji_fromaddr", (as_bin_value*) &ji_fromaddr);
	as_integer_init(&ji_qrank, pjob->ji_qrank);
	as_operations_add_write(&ops, "ji_qrank", (as_bin_value*) &ji_qrank);
	sprintf(pjob->ji_savetm, "%lu", db_time_now(0));
	as_integer_init(&ji_savetm, strtoul(pjob->ji_savetm, NULL, 10));
	as_operations_add_write(&ops, "ji_savetm", (as_bin_value*) &ji_savetm);

	if (savetype == PBS_INSERT_DB) {
		as_integer_init(&ji_creattm, db_time_now(0));
		as_operations_add_write(&ops, "ji_creattm", (as_bin_value*) &ji_creattm);
	}
	
	if (savetype != PBS_UPDATE_DB_QUICK) {
		if (convert_db_attr_list_to_asmap(&attrmap, &pjob->attr_list) < 0) 
			return -1;

		as_map_policy_init(&map_policy);
		as_operations_add_map_put_items(&ops, "attributes", &map_policy, (as_map*) &attrmap);
	}

	as_policy_operate_init(&op_policy);
	op_policy.key = AS_POLICY_KEY_SEND;
	
	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		sprintf(conn->conn_db_err, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	
	return 0;
}

static int
load_job(as_record* rec, pbs_db_job_info_t *pjob)
{
	as_map *attrmap;
	pjob->ji_state = as_record_get_int64(rec, "ji_state", INT64_MAX);
	pjob->ji_substate = as_record_get_int64(rec, "ji_substate", INT64_MAX);
	pjob->ji_svrflags = as_record_get_int64(rec, "ji_svrflags", INT64_MAX);
	pjob->ji_ordering = as_record_get_int64(rec, "ji_ordering", INT64_MAX);
	pjob->ji_priority = as_record_get_int64(rec, "ji_priority", INT64_MAX);
	pjob->ji_stime = as_record_get_int64(rec, "ji_stime", INT64_MAX);
	pjob->ji_endtBdry = as_record_get_int64(rec, "ji_endtBdry", INT64_MAX);
	strcpy(pjob->ji_queue, as_record_get_str(rec, "ji_queue"));
	strcpy(pjob->ji_destin, as_record_get_str(rec, "ji_destin"));
	pjob->ji_un_type = as_record_get_int64(rec, "ji_un_type", INT64_MAX);
	pjob->ji_exitstat = as_record_get_int64(rec, "ji_exitstat", INT64_MAX);
	pjob->ji_quetime = as_record_get_int64(rec, "ji_quetime", INT64_MAX);
	pjob->ji_rteretry = as_record_get_int64(rec, "ji_rteretry", INT64_MAX);
	pjob->ji_fromsock = as_record_get_int64(rec, "ji_fromsock", INT64_MAX);
	pjob->ji_fromaddr = as_record_get_int64(rec, "ji_fromaddr", INT64_MAX);
	pjob->ji_qrank = as_record_get_int64(rec, "ji_qrank", INT64_MAX);
	sprintf(pjob->ji_savetm, "%lu", as_record_get_int64(rec, "ji_savetm", INT64_MAX));
	sprintf(pjob->ji_creattm, "%lu", as_record_get_int64(rec, "ji_creattm", INT64_MAX));

	attrmap = as_record_get_map(rec, "attributes");
	if (convert_asmap_to_db_attr_list((as_hashmap *) attrmap, &pjob->attr_list) < 0) 
		return -1;

	return 0;
}

/**
 * @brief
 *	Load job data from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in/out]obj  - Load job information into this object where
 *			jobid = obj->pbs_db_un.pbs_db_job->ji_jobid
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	>1 - Number of attributes
 * @retval 	-2 -  Success but data same as old, so not loading data (but locking if lock requested)
 *
 */
int
impl_db_load_job(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int lock)
{
	pbs_db_job_info_t *pjob = obj->pbs_db_un.pbs_db_job;
	int rc;
	as_key key; /* jobid */
	as_error err;
	as_record* p_rec = NULL;
	aerospike *as = (aerospike *) conn->conn_db_handle;

	as_key_init_str(&key, g_namespace, "job", pjob->ji_jobid);
	if (aerospike_key_get(as, &err, NULL, &key, &p_rec) != AEROSPIKE_OK) {
		sprintf(conn->conn_db_err, "aerospike_key_get() returned %d - %s\n", err.code, err.message);
		as_record_destroy(p_rec);
		return -1;
	}

	load_job(p_rec, pjob);
	as_record_destroy(p_rec);
	
	return 0;
}

static
bool job_callback(const as_val *val, void* udata)
{
	pbs_db_obj_info_t obj;
	pbs_db_job_info_t dbjob;
	pbs_db_job_info_t *pjob = &dbjob;
	db_query_state_t *state = (db_query_state_t *) udata;
	as_record* rec = NULL;

	obj.pbs_db_obj_type = PBS_DB_JOB;
	obj.pbs_db_un.pbs_db_job = pjob;

	rec = as_record_fromval(val);
	if (!rec) return false;

	strcpy(pjob->ji_jobid, rec->key.value.string.value);
	load_job(rec, pjob);
	as_record_destroy(rec);
	state->query_cb(&obj, &state->count);

	pbs_db_reset_obj(&obj); // free attribute list
	
	return true;
}

/**
 * @brief
 *	Find jobs
 *
 * @param[in]	conn - Connection handle
 * @param[out]  st   - The cursor state variable updated by this query
 * @param[in]	obj  - Information of job to be found
 * @param[in]	opts - Any other options (like flags, timestamp)
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows found
 *
 */
int
impl_db_find_job(pbs_db_conn_t *conn, void *st, pbs_db_obj_info_t *obj, pbs_db_query_options_t *opts)
{
	db_query_state_t *state = (db_query_state_t *) st;
	pbs_db_job_info_t *pdjob = obj->pbs_db_un.pbs_db_job;
	int rc;
	aerospike *as = (aerospike *) conn->conn_db_handle;
	as_query query;
	int savetm;
	as_error err;

	if (!state)
		return -1;

	as_query_init(&query, g_namespace, "job");
	if (opts != NULL && opts->flags == FIND_JOBS_BY_QUE) {
		as_query_where(&query, "ji_query", as_string_equals(opts->queue));
	} else if (opts != NULL && opts->timestamp){
		as_query_where_inita(&query, 1);
		savetm = strtoul(opts->timestamp, NULL, 10);
		as_query_where(&query, "ji_savetm", as_integer_range(savetm, db_time_now(0)));
	}

	state->row = 0;
	state->count = 0;

	if (aerospike_query_foreach(as, &err, NULL, &query, job_callback, state) != AEROSPIKE_OK) {
		sprintf(conn->conn_db_err,"aerospike_query_foreach() returned %d - %s", err.code, err.message);
		as_query_destroy(&query);
		return -1;
	}
	as_query_destroy(&query);

	return 0;
}


/**
 * @brief
 *	Delete the job from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Job information
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows deleted
 *
 */
int
impl_db_delete_job(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_job_info_t *pj = obj->pbs_db_un.pbs_db_job;
	int rc = 0;

	return rc;
err:
	return -1;
}

/**
 * @brief
 *	Insert job script
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Job script object
 * @param[in]	savetype - Just a place holder here. Maintained the same prototype as with
 * 		           the other database save functions since this is called through function pointer.
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
impl_db_save_jobscr(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int savetype)
{
	return 0;
}

/**
 * @brief
 *	load job script
 *
 * @param[in]	  conn - Connection handle
 * @param[in/out] obj  - Job script is loaded into this object
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
impl_db_load_jobscr(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int lock)
{
	return 0;
}



/**
 * @brief
 *	Deletes attributes of a job
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Job information
 * @param[in]	obj_id  - Job id
 * @param[in]	attr_list - List of attributes
 *
 * @return      Error code
 * @retval	 0 - Success
 * @retval	-1 - On Failure
 *
 */
int
impl_db_del_attr_job(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, void *obj_id, pbs_db_attr_list_t *attr_list)
{
	return 0;
}

/**
 * @brief
 *	Frees allocate memory of an Object
 *
 * @param[in]	obj - pbs_db_obj_info_t containing the DB object
 *
 * @return      None
 *
 */
void
impl_db_reset_job(pbs_db_obj_info_t *obj)
{
	free_db_attr_list(&(obj->pbs_db_un.pbs_db_job->attr_list));
	obj->pbs_db_un.pbs_db_job->ji_jobid[0] = '\0';
	obj->pbs_db_un.pbs_db_job->ji_savetm[0] = '\0';
}

int
pbs_db_get_maxjobid(pbs_db_conn_t *conn,  long long *jobid)
{
	return 0;
}

int
pbs_db_get_statecounts(pbs_db_conn_t *conn, char *qname, int statesize, int *statearray)
{
	int rc;
	int i;
	int state;
	long long jobcount;
	
	for(i = 0; i < statesize; i++) {
		statearray[i] = 0;
	}

	return 0;
}
