/*
 * Copyright (C) 1994-2018 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */


/**
 * @file    db_impl_sched.c
 *
 * @brief
 *      Implementation of the sched data access functions for postgres
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include "pbs_db.h"
#include "db_impl.h"

/**
 *@brief
 *	Save (insert/update) a new/existing sched
 *
 * @param[in]	conn - The connnection handle
 * @param[in]	obj  - The sched object to save
 * @param[in]	savetype - PBS_UPDATE_DB_QUICK/PBS_UPDATE_DB_FULL/PBS_INSERT_DB
 *
 * @return      Error code
 * @retval	-1 - Execution of prepared statement failed
 * @retval	 0 - Success and > 0 rows were affected
 * @retval	 1 - Execution succeeded but statement did not affect any rows
 *
 */
int
impl_db_save_sched(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_sched_info_t *pschd = obj->pbs_db_un.pbs_db_sched;
	int numbins = 1; /* default minimum */
	
    as_key key;
	as_integer  sched_savetm;
	as_integer  sched_creattm;
	as_hashmap attrmap;
	as_map_policy map_policy;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
    char sched_partition[100];
	aerospike *as = (aerospike *) conn->conn_db_handle;

	if (savetype != PBS_UPDATE_DB_QUICK) numbins++; /* for attributes */	
	if (savetype == PBS_INSERT_DB) numbins++; /* for createtm */

	as_operations_inita(&ops, numbins);
    strcpy(sched_partition, pschd->sched_name);
    if (pschd->partition_name && pschd->partition_name[0] != '\0') {
        strcat(sched_partition, ".");
        strcat(sched_partition, pschd->partition_name);
    }
	as_key_init_str(&key, g_namespace, "scheduler", sched_partition);	
	
	sprintf(pschd->sched_savetm, "%lu", db_time_now(0));
	as_integer_init(&sched_savetm, strtoul(pschd->sched_savetm, NULL, 10));
	as_operations_add_write(&ops, "sched_savetm", (as_bin_value*) &sched_savetm);

	if (savetype == PBS_INSERT_DB) {
		as_integer_init(&sched_creattm, db_time_now(0));
		as_operations_add_write(&ops, "sched_creattm", (as_bin_value*) &sched_creattm);
	}
	
	if (savetype != PBS_UPDATE_DB_QUICK) {
		if (convert_db_attr_list_to_asmap(&attrmap, &pschd->attr_list) < 0) 
			return -1;

		as_map_policy_init(&map_policy);
		as_operations_add_map_put_items(&ops, "attributes", &map_policy, (as_map*) &attrmap);
	}

	as_policy_operate_init(&op_policy);
	op_policy.key = AS_POLICY_KEY_SEND;

	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		sprintf(conn->conn_db_err, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	
	return 0;
}

static int
load_sched(as_record* rec, pbs_db_sched_info_t *pschd)
{
	as_map *attrmap;
	
	sprintf(pschd->sched_savetm, "%lu", as_record_get_int64(rec, "sched_savetm", INT64_MAX));
	sprintf(pschd->sched_creattm, "%lu", as_record_get_int64(rec, "sched_creattm", INT64_MAX));

	attrmap = as_record_get_map(rec, "attributes");
	if (convert_asmap_to_db_attr_list((as_hashmap *) attrmap, &pschd->attr_list) < 0) 
		return -1;

    return 0;
}

/**
 * @brief
 *	Load sched data from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in/out]obj  - Load sched information into this object
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	>1 - Number of attributes
 * @retval 	-2 -  Success but data same as old, so not loading data (but locking if lock requested)
 *
 */
int
impl_db_load_sched(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int lock)
{
	pbs_db_sched_info_t *pschd = obj->pbs_db_un.pbs_db_sched;
	int rc;
	as_key key; /* sched name + parition id */
	as_error err;
	as_record* p_rec = NULL;
    char sched_partition[100];
    aerospike *as = (aerospike *) conn->conn_db_handle;

    strcpy(sched_partition, pschd->sched_name);
    if (pschd->partition_name && pschd->partition_name[0] != '\0') {
        strcat(sched_partition, ".");
        strcat(sched_partition, pschd->partition_name);
    }

	as_key_init_str(&key, g_namespace, "scheduler", sched_partition);
	if (aerospike_key_get(as, &err, NULL, &key, &p_rec) != AEROSPIKE_OK) {
		sprintf(conn->conn_db_err, "aerospike_key_get() returned %d - %s\n", err.code, err.message);
		as_record_destroy(p_rec);
		return -1;
	}

	load_sched(p_rec, pschd);
	as_record_destroy(p_rec);
	
	return 0;
}


static
bool sched_callback(const as_val *val, void* udata)
{
	pbs_db_obj_info_t obj;
	pbs_db_sched_info_t dbsched;
	pbs_db_sched_info_t *pschd = &dbsched;
	db_query_state_t *state = (db_query_state_t *) udata;
	as_record* rec = NULL;

	obj.pbs_db_obj_type = PBS_DB_SCHED;
	obj.pbs_db_un.pbs_db_sched = pschd;

	rec = as_record_fromval(val);
	if (!rec) return false;

	strcpy(pschd->sched_name, rec->key.value.string.value);
	load_sched(rec, pschd);
	as_record_destroy(rec);
	state->query_cb(&obj, &state->count);
	pbs_db_reset_obj(&obj); // free attribute list
	
	return true;
}

/**
 * @brief
 *	Find jobs
 *
 * @param[in]	conn - Connection handle
 * @param[out]  st   - The cursor state variable updated by this query
 * @param[in]	obj  - Information of job to be found
 * @param[in]	opts - Any other options (like flags, timestamp)
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows found
 *
 */
int
impl_db_find_sched(pbs_db_conn_t *conn, void *st, pbs_db_obj_info_t *obj, pbs_db_query_options_t *opts)
{
	db_query_state_t *state = (db_query_state_t *) st;
	pbs_db_sched_info_t *pschd = obj->pbs_db_un.pbs_db_sched;
	int rc;
	aerospike *as = (aerospike *) conn->conn_db_handle;
	as_query query;
	as_query_init(&query, g_namespace, "scheduler");
	int savetm;
	as_error err;

	if (!state)
		return -1;

	if (opts != NULL && opts->timestamp) {
		as_query_where_inita(&query, 1);
		savetm = strtoul(opts->timestamp, NULL, 10);
		as_query_where(&query, "sched_savetm", as_integer_range(savetm, db_time_now(0)));
	}

	state->row = 0;
	state->count = 0;

	if (aerospike_query_foreach(as, &err, NULL, &query, sched_callback, state) != AEROSPIKE_OK) {
		sprintf(conn->conn_db_err, "aerospike_query_foreach() returned %d - %s", err.code, err.message);
		as_query_destroy(&query);
		return -1;
	}
	as_query_destroy(&query);

	return 0;
}

/**
 * @brief
 *	Delete the sched from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - sched information
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows deleted
 *
 */
int
impl_db_delete_sched(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_sched_info_t *pj = obj->pbs_db_un.pbs_db_sched;
	int rc = 0;

	return rc;
err:
	return -1;
}


/**
 * @brief
 *	Deletes attributes of a sched
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - sched information
 * @param[in]	obj_id  - sched name + partition id
 * @param[in]	attr_list - List of attributes
 *
 * @return      Error code
 * @retval	 0 - Success
 * @retval	-1 - On Failure
 *
 */
int
impl_db_del_attr_sched(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, void *obj_id, pbs_db_attr_list_t *attr_list)
{
	return 0;
}

/**
 * @brief
 *	Frees allocate memory of an Object
 *
 * @param[in]	obj - pbs_db_obj_info_t containing the DB object
 *
 * @return      None
 *
 */
void
impl_db_reset_sched(pbs_db_obj_info_t *obj)
{
	free_db_attr_list(&(obj->pbs_db_un.pbs_db_sched->attr_list));
	obj->pbs_db_un.pbs_db_sched->sched_name[0] = '\0';
    obj->pbs_db_un.pbs_db_sched->partition_name[0] = '\0';
	obj->pbs_db_un.pbs_db_sched->sched_savetm[0] = '\0';
}
