/*
 * Copyright (C) 1994-2021 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */

#include <stdlib.h>
#include <unistd.h>
#include <pbs_config.h>   /* the master config generated by configure */
#include <errno.h>
#include <arpa/inet.h>
#ifndef WIN32
#include <sys/un.h>
#include <errno.h>
#include <signal.h>
#include <openssl/sha.h>
#endif
#include "cmds.h"
#include "credential.h"
#include "attribute.h"
#include "pbs_idx.h"

static int child_process = 0;

/**
 * @brief
 *  log a message to syslog
 *
 * @param cmd - name of cmd/utility calling it
 * @param msg - message to be logged
 *
 */
void
log_syslog(char *cmd, char *msg)
{
	openlog(cmd, LOG_PID | LOG_CONS | LOG_NOWAIT, LOG_USER);
	syslog(LOG_ERR, "%s", msg);
	closelog();
}

/******************************************************************************
 * foreground/background process communication routines
 * 
 *****************************************************************************/


/**
 * @brief
 *	Helper function to get the pbs conf file path, and
 *	convert it to a string, later added to the filename
 *	(pipe or unix domain socket filename) that is used
 *	for communications between the front-end and
 *	background qsub processes.
 *	The path to the pbs conf file is converted to a string
 *	by replacing the slashes with underscore char.
 *	If PBS_CONF_FILE is not set, then an empty string is returned.
 *
 * @return - The string representing path to the pbs conf file
 *
 */
static char *
get_conf_path(void)
{
	char *cnf = getenv("PBS_CONF_FILE");
	/* static pointer so we can free heap memory from previous invocation of this function */
	static char *dup_cnf_path = NULL;
	char *p;

	if (cnf) {
		p = strdup(cnf);
		if (p) {
			free(dup_cnf_path);
			dup_cnf_path = p;
			while (*p) {
				if (*p == '/' || *p == ' ' || *p == '.')
					*p = '_';
				p++;
			}
		}
		return dup_cnf_path;
	} else if (dup_cnf_path) {
		return dup_cnf_path;
	} else {
		return "";
	}
}

/**
 * @brief
 *	Sets the filename to be used for the unix domain socket based comm.
 *	This is formed by appending the UID and the target server name to the
 *	filename.
 *
 * @param[in] cmd - the CLI utility that invoked this
 * @param[in] tmpdir - tmpdir set by the caller
 * @param[in] server - the server hostname
 * @param[in] cred_name - cred_name used in case of qsub
 * 
 * @param[out] fname - filename to be used by the unix domain socket to connect (static)
 *
 */
char *
get_comm_filename(char *cmd, char *tmpdir, char *server, char *cred_name)
{
	char *env_svr = getenv(PBS_CONF_SERVER_NAME);
	char *env_port = getenv(PBS_CONF_BATCH_SERVICE_PORT);
	char *psi_var = pbs_get_conf_var(PBS_CONF_SERVER_INSTANCES);
	int count = 0;
	char buf[LARGE_BUF_LEN];
	int len;
	unsigned char hash[SHA_DIGEST_LENGTH];
	static char fname[MAXPIPENAME] = {'\0'}; /* the filename used as the pipe name */
	int i;

	count = snprintf(fname, MAXPIPENAME, "%s/%s_%.16s_%lu_%.8s_%.32s_%.16s_%.5s_%s",
		tmpdir,
		cmd,
		((server == NULL || server[0] == 0) ?
		"default" : server),
		(unsigned long int)getuid(),
		cred_name,
		get_conf_path(),
		env_svr ? env_svr : "",
		env_port ? env_port : "",
		psi_var ? psi_var : ""
		);

	if (count >= MAXPIPENAME) {
		count = snprintf(fname, MAXPIPENAME, "%s/pbs_", TMP_DIR);
		len = snprintf(buf, MAXPIPENAME, "%.16s_%lu_%.8s_%.32s_%.16s_%.5s_%s",
			 ((server == NULL || server[0] == 0) ? "default" : server),
			 (unsigned long int) getuid(),
			 cred_name,
			 get_conf_path(),
			 (env_svr == NULL) ? "" : env_svr,
			 (env_port == NULL) ? "" : env_port,
			 psi_var ? psi_var : "");

		if (len + count < MAXPIPENAME) {
			pbs_strncpy(fname + count, buf, MAXPIPENAME - count);
		} else {
			if (SHA1((const unsigned char *) buf, SHA_DIGEST_LENGTH, (unsigned char *) &hash)) {
				for (i = 0; i < SHA_DIGEST_LENGTH; i++)
					sprintf(buf + (i * 2), "%02x", hash[i]);
					
				buf[SHA_DIGEST_LENGTH*2] = 0;
			}
			pbs_strncpy(fname + count, buf, MAXPIPENAME - count);
		}
	}

	free(psi_var);

	return fname;
}

/**
 * @brief
 *  connect and talk to background CLI daemon process
 *
 * @param fname - name of communication file to be used
 *
 * @return - error code/communication file fd
 * @retval -1 failure
 * @retval != -1 communication file fd
 *
 */
int
talk_to_bg(char *fname)
{
	int sock = -1; /* UNIX domain socket for talking to daemon */
	struct sockaddr_un s_un;
	sigset_t newsigmask;

again:
	if (access(fname, F_OK) == 0) {
		/* pass information to daemon */
		/* wait for job-id or error string */
		if ((sock = socket(AF_UNIX, SOCK_STREAM, 0)) == -1)
			return -1;

		s_un.sun_family = AF_UNIX;
		snprintf(s_un.sun_path, sizeof(s_un.sun_path), "%s", fname);

		if (connect(sock, (const struct sockaddr *) &s_un, sizeof(s_un)) == -1) {
			int refused = (errno == ECONNREFUSED);

			close(sock);
			if (refused) {
				/* daemon unavailable, del temp file, restart */
				if (unlink(fname) != 0)
					return -1;

				sock = -1;
				goto again;
			}
			return -1;
		}

		/* block SIGPIPE on write() failures. */
		sigemptyset(&newsigmask);
		sigaddset(&newsigmask, SIGPIPE);
		sigprocmask(SIG_BLOCK, &newsigmask, NULL);
	}
	return sock;
}

/**
 * @brief
 *  fork to background and wait for commands from foreground
 *
 * @param cmd - cli cmd name that invoked this
 * @param fname - name of communication file to be used
 * @param sd_svr - socket fd of connection to pbs server
 * @param talk_to_fg - function pointer to callback when 
 *                     we want to talk to foreground
 *
 */
void
go_bg(char *cmd, char *fname, int sd_svr, int (*talk_to_fg)(int sock, int sd_svr, char **err_op))
{
	int sock, bindfd = -1;
	struct sockaddr_un s_un;
	struct sockaddr from;
	socklen_t fromlen;
	int rc;
	fd_set readset;
	fd_set workset;
	struct timeval timeout;
	int n, maxfd;
	mode_t cmask = 0077;
	sigset_t newsigmask, oldsigmask;
	char *err_op = "";
	char log_buf[LOG_BUF_SIZE];
	int pid;
	FILE *dummy;
	int cred_timeout = 0;
	time_t connect_time = time(0);

	pid = fork();
	if (pid == -1)
		return;
	
	if (pid > 0) {
		/* let the parent wait a few milliseconds, so we can set up the background daemon */
		usleep(200); 
		return;
	}

	/* child process */
	child_process = 1; /* identify myself as the background daemon */
	
	/* set stdin, stdout and stderr to NULL device */
	dummy = fopen(NULL_DEVICE, "r");
	dup2(fileno(dummy), fileno(stdin));

	dummy = fopen(NULL_DEVICE, "w");
	dup2(fileno(dummy), fileno(stdout));
	
	dummy = fopen(NULL_DEVICE, "w");
	dup2(fileno(dummy), fileno(stderr));

	/*
	 * Try to become the session leader.
	 * If that fails, exit with a syslog message
	 */
	if (setsid() == -1) {
		err_op = "setsid failed";
		goto error;
	}

	/* set single threaded mode */
	pbs_client_thread_set_single_threaded_mode();

	/* set umask so socket file created is only accessible by same user */
	umask(cmask);
	sigemptyset(&newsigmask);
	sigaddset(&newsigmask, SIGPIPE);
	sigprocmask(SIG_BLOCK, &newsigmask, NULL);

	/* start up a unix domain socket to listen */
	if ((bindfd = socket(AF_UNIX, SOCK_STREAM, 0)) == -1) {
		err_op = "socket";
		goto error;
	}

	s_un.sun_family = AF_UNIX;
	snprintf(s_un.sun_path, sizeof(s_un.sun_path), "%s", fname);

	if (bind(bindfd, (const struct sockaddr *) &s_un, sizeof(s_un)) == -1) {
		if (errno == EADDRINUSE)
			exit(1); /* dont go to error */
		else {
			err_op = "bind";
			goto error;
		}
	}

	FD_ZERO(&readset);
	if (listen(bindfd, 1) != 0) {
		err_op = "listen";
		goto error;
	}

	FD_SET(bindfd, &readset);
	FD_SET(sd_svr, &readset);
	maxfd = (bindfd > sd_svr) ? bindfd : sd_svr;
	while (1) {

		err_op = "";

		memcpy(&workset, &readset, sizeof(readset));

		timeout.tv_usec = 0;
		/* since timeout gets reset on Linux */
		if (cred_timeout == 1)
			timeout.tv_sec = CLI_DMN_TIMEOUT_SHORT; /* Short timeout to allow any foreground process to finsih before exiting */
		else
			timeout.tv_sec = CLI_DMN_TIMEOUT_LONG;

		n = select(maxfd + 1, &workset, NULL, NULL, &timeout);
		if (n == 0)
			goto out; /* daemon timed out waiting for sd_svr from foreground */
		else if (n == -1) {
			err_op = "select failed";
			goto error;
		}

		/*
		 * check if we are past the credential timeout
		 * Error out even if it is close to CREDENTIAL_LIFETIME, as
		 * request could take a while to reach server and get processed
		 * Qsub then does a regular submit (new connection)
		 */
		if (cred_timeout == 0 && ((time(0) - connect_time) > (CREDENTIAL_LIFETIME - CLI_DMN_TIMEOUT_LONG))) {
			unlink(fname);
			cred_timeout = 1;
		}

		if (FD_ISSET(sd_svr, &workset)) {
			if (recv(sd_svr, &rc, 1, MSG_OOB) < 1)
				goto out;
		}

		/* accept the connection */
		fromlen = sizeof(from);
		if ((sock = accept(bindfd, &from, &fromlen)) == -1) {
			err_op = "accept";
			goto error;
		}

		sigemptyset(&newsigmask);
		sigaddset(&newsigmask, SIGXCPU);
		sigaddset(&newsigmask, SIGXFSZ);
		sigaddset(&newsigmask, SIGTSTP);
		sigaddset(&newsigmask, SIGINT);
		sigaddset(&newsigmask, SIGSTOP);
		sigaddset(&newsigmask, SIGTERM);
		sigaddset(&newsigmask, SIGTSTP);
		sigaddset(&newsigmask, SIGALRM);
		sigaddset(&newsigmask, SIGQUIT);
		sigaddset(&newsigmask, SIGUSR1);
		sigaddset(&newsigmask, SIGUSR2);
		sigprocmask(SIG_BLOCK, &newsigmask, &oldsigmask);

		rc = (*talk_to_fg)(sock, sd_svr, &err_op);
		
		close(sock);

		if (rc == 1)
			goto out;
		else if (rc == 2)
			goto error;

		sigprocmask(SIG_SETMASK, &oldsigmask, NULL);

		/* close the handles else pipes will hang */
		fflush(stdout);
		fflush(stderr);

		/* 
		 * close stdout, stderr and replace with dummy file handles
		 * replacing with dummy is essential else further dup2 
		 * will fail
		 */
		dummy = fopen(NULL_DEVICE, "w");
		dup2(fileno(dummy), fileno(stdout));
		
		dummy = fopen(NULL_DEVICE, "w");
		dup2(fileno(dummy), fileno(stderr));
	}

out:
	close(bindfd);
	unlink(fname);
	exit(0);

error:
	sprintf(log_buf, "Background %s daemon: Failed at %s, errno=%d\n", cmd, err_op, errno);
	CLI_DBPRT((stderr, log_buf))
	log_syslog(cmd, log_buf);
	
	unlink(fname);
	close(bindfd);

	exit(1);
}

/**
 * @brief
 *	Receive data of bufsize length from the peer. Used for communications
 * 	between the foreground and background qsub processes.
 *
 * @param[in] sock - socket to receive data from
 * @param[in] buf - the buf to receive data into
 * @param[in] bufisze - the amount of data to read
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
dorecv(int sock, char *buf, int bufsize)
{
	int bytes = 0;
	char *p = buf;
	int remaining = bufsize;
	int rc;

	do {
		errno = 0;
		rc = read(sock, p, remaining);
		if (rc == -1)
			return -1;
		if (rc == 0)
			break;
		bytes += rc;
		p += rc;
		remaining -= rc;
	} while (bytes < bufsize);

	if (bytes != bufsize)
		return -1;

	return 0;
}

/**
 * @brief
 *	Send data of bufsize length to the peer. Used for communications
 * 	between the foreground and background qsub processes.
 *
 * @param[in] sock - socket to receive data from
 * @param[in] buf - the buf to send data from
 * @param[in] bufsize - the amount of data to send
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
dosend(int sock, char *buf, int bufsize)
{
	int bytes = 0;
	int rc;
	char *p = buf;
	int remaining = bufsize;
	do {
		/*
		 * For systems with MSG_NOSIGNAL defined (e.g. Linux 2.2 and later),
		 * we use send() rather than write() in order to block the SIGPIPE
		 * that qsub would receive if the remote side closes the stream. For
		 * other systems, the exit_on_sigpipe() handler gets called.
		 */
		errno = 0;
#ifdef MSG_NOSIGNAL
		rc = send(sock, p, remaining, MSG_NOSIGNAL);
#else
		rc = write(sock, p, remaining);
#endif
		if (rc == -1)
			return -1;
		if (rc == 0)
			break;
		bytes += rc;
		p += rc;
		remaining -= rc;
	} while (bytes < bufsize);

	if (bytes != bufsize)
		return -1;
	return 0;
}

/**
 * @brief
 *	Send the attrl list to the background qsub process. This is the
 * 	attribute list that was created by the foreground process based on
 *	the options that the user has provided to qsub.
 *
 * @param[in] sock - socket to receive data from
 * @parma[in] attrib - List of attributes created by foreground qsub process
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
send_attrl(int sock, struct attrl *attrib)
{
	int bufused = 0;
	int len_n = 0, len_r = 0, len_v = 0;
	char *p, *tmp;
	int lenreq = 0;
	int bufsize = DMN_BUF_SIZE;
	char *buf = malloc(bufsize);

	if (!buf)
		return -1;

	while (attrib) {
		len_n = strlen(attrib->name) + 1;
		if (attrib->resource)
			len_r = strlen(attrib->resource) + 1;
		else
			len_r = 0;
		len_v = strlen(attrib->value) + 1;

		lenreq = len_n + len_r + len_v + 3 * sizeof(int);
		if (lenreq >= (bufsize - bufused)) {
			bufsize *= 2;
			if (lenreq > (bufsize - bufused))
				bufsize += lenreq;
			tmp = realloc(buf, bufsize);
			if (!tmp) {
				free(buf);
				return -1;
			}
			buf = tmp;
		}

		/* write the lengths */
		p = buf + bufused;
		memmove(p, &len_n, sizeof(int));
		p += sizeof(int);
		memmove(p, &len_r, sizeof(int));
		p += sizeof(int);
		memmove(p, &len_v, sizeof(int));
		p += sizeof(int);

		/* now add the strings */
		memmove(p, attrib->name, len_n);
		p += len_n;
		if (len_r > 0) {
			memmove(p, attrib->resource, len_r);
			p += len_r;
		}
		memmove(p, attrib->value, len_v);
		p += len_v;

		bufused += lenreq;

		attrib = attrib->next;
	}
	if ((dosend(sock, (char *) &bufused, sizeof(int)) != 0) ||
		(dosend(sock, buf, bufused) != 0))
		return -1;

	free(buf);
	return 0;
}

/**
 * @brief
 * 	Send a null terminated string to the peer process. Used by backrgound and
 * 	foreground qsub processes to communicate error-strings, job-ids etc.
 *
 * @param[in] sock - socket to receive data from
 * @parma[in] str - null terminated string to send
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
send_string(int sock, char *str)
{
	if (!str)
		str="";
	int len = strlen(str) + 1;

	if ((dosend(sock, (char *) &len, sizeof(int)) != 0) ||
		(dosend(sock, str, len) != 0))
		return -1;

	return 0;
}

/**
 * @brief
 *	Recv the attrl list from the foreground qsub process. This is the
 * 	attribute list that was created by the foreground process based on
 * 	the options that the user has provided to qsub.
 *
 * @param[in] sock - socket to receive data from
 * @parma[in] attrib - List of attributes created by foreground qsub process
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
recv_attrl(int sock, struct attrl **attrib)
{
	int recvlen = 0;
	struct attrl *attr = NULL;
	char *p;
	int len_n = 0, len_r = 0, len_v = 0;
	char *buf;

	if (dorecv(sock, (char *) &recvlen, sizeof(int)) != 0)
		return -1;
	
	if (!(buf = malloc(recvlen + 1)))
		return -1;

	if (dorecv(sock, buf, recvlen) != 0) {
		free(buf);
		return -1;
	}

	p = buf;
	while (p - buf < recvlen) {
		memmove(&len_n, p, sizeof(int));
		p += sizeof(int);
		memmove(&len_r, p, sizeof(int));
		p += sizeof(int);
		memmove(&len_v, p, sizeof(int));
		p += sizeof(int);

		if (len_r > 0)
			set_attr_resc_error_exit(&attr, p, p + len_n, p + len_n + len_r);
		else	
			set_attr_error_exit(&attr, p, p + len_n);
		p += len_n + len_r + len_v;
	}
	*attrib = attr;
	free(buf);
	return 0;
}

/**
 * @brief
 *  Recv a null terminated string from the peer process. Used by background and
 * 	foreground qsub processes to communicate error-strings, job-ids etc
 *
 * @param[in] sock - socket to receive data from
 * @parma[out] buf - pointer to the newly-malloced string.
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
recv_dyn_string(int sock, char **buf)
{
	int len = 0;
	int rc = -1;

	if (dorecv(sock, (char *) &len, sizeof(int)) == 0) {
		if ((*buf = malloc(len + 1))) {
			rc = dorecv(sock, *buf, len);
			if (rc == -1) {
				free(*buf);
				*buf = NULL;
			}
		}
	}
	return rc;
}

/**
 * @brief
 *  Recv a null terminated string from the peer process. Used by backrgound and
 * 	foreground qsub processes to communicate error-strings, job-ids etc.
 *
 * @param[in] sock - socket to receive data from
 * @param[in] buf - pointer to buffer to recieve data into
 * @param[in] size - size of data buffer
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
recv_string(int sock, char *buf, int size)
{
	char *dynbuf = NULL;
	
	if (recv_dyn_string(sock, &dynbuf) != 0)
		return -1;

	if (dynbuf == NULL)
		buf[0] = '\0';
	else {
		pbs_strncpy(buf, dynbuf, size);
		free(dynbuf);
	}

	return 0;
}

/**
 * Sends given file descriptior via given socket
 *
 * @param[in] sock - socket to be used for fd sending
 * @param[in] fd to be sent
 * 
 * @return sendmsg result
 *
 * @note socket should be (PF_UNIX, SOCK_DGRAM)
 */
int 
send_fd(int sock, int fd) 
{
    char dummy = '$';
    struct msghdr msg;
    struct iovec iov;
	int *data;

    char cmsgbuf[CMSG_SPACE(sizeof(int))];

    iov.iov_base = &dummy;
    iov.iov_len = sizeof(dummy);

    msg.msg_name = NULL;
    msg.msg_namelen = 0;
    msg.msg_iov = &iov;
    msg.msg_iovlen = 1;
    msg.msg_flags = 0;
    msg.msg_control = cmsgbuf;
    msg.msg_controllen = CMSG_LEN(sizeof(int));

    struct cmsghdr* cmsg = CMSG_FIRSTHDR(&msg);
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    cmsg->cmsg_len = CMSG_LEN(sizeof(int));

	data = (int *) CMSG_DATA(cmsg);
    *data  = fd;

    int ret = sendmsg(sock, &msg, 0);

    if (ret == -1) {
        printf("sendmsg failed with %s", strerror(errno));
    }

    return 0;
}

/**
 * Receives file descriptor using given socket
 *
 * @param sock - socket to be used for fd recepion
 * 
 * @return received file descriptor; -1 if failed
 *
 * @note socket should be (PF_UNIX, SOCK_DGRAM)
 * 
 */
int 
recv_fd(int sock) 
{
    int len;
    int fd;
    char buf[1];
    struct iovec iov;
    struct msghdr msg;
    struct cmsghdr *cmsg;
    char cms[CMSG_SPACE(sizeof(int))];

    iov.iov_base = buf;
    iov.iov_len = sizeof(buf);

    msg.msg_name = 0;
    msg.msg_namelen = 0;
    msg.msg_iov = &iov;
    msg.msg_iovlen = 1;
    msg.msg_flags = 0;
    msg.msg_control = (caddr_t) cms;
    msg.msg_controllen = sizeof cms;

    len = recvmsg(sock, &msg, 0);

    if (len < 0) {
        printf("recvmsg failed with %s", strerror(errno));
        return -1;
    }

    if (len == 0) {
        printf("recvmsg failed no data");
        return -1;
    }

    cmsg = CMSG_FIRSTHDR(&msg);
    memmove(&fd, CMSG_DATA(cmsg), sizeof(int));
    return fd;
}